### ISSUE TITLE
Modification du design 

### ISSUE THREAD

**Issue by AboubakrCH** [institut-galilee/guessless#1]
Ce qui était prévue c'est d'utiliser deux panneaux led, qui vont servir à la fois pour déposer l'objet et d'afficher les infos sur cet objet.
Je propose d'utiliser un seul panneau qui va servir pour déposer l'objet avec l'ajout d'un petit écran, ce dernier affichera les informations.

**Comment by maherlaaroussi** [comment]
Il est vrai que l'affichage sur un écran (IPS, LCD ...) serait de plus bonne qualité que les panneaux LEDs seuls. Donc proposition intéressante.

**Comment by othmaneMchouat** [comment]
[Guessless.pdf](https://github.com/institut-galilee/guessless/files/2823487/Guessless.pdf)
Je vous propose le designe suivant

**Comment by maherlaaroussi** [comment]
J'approuve mais il y aura du changement à faire au vu des problèmes techniques qu'on rencontrera !
