### ISSUE TITLE
Cablâge du panneau LED

### ISSUE THREAD

**Issue by maherlaaroussi** [institut-galilee/guessless#19]
Faire en sorte que le panneau LED fonctionne correctement avec un Raspberry.

**Comment by maherlaaroussi** [comment]
On a commandé ce matériel :  
* https://www.amazon.fr/gp/product/B01MDPCKDC/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1
* https://www.amazon.fr/gp/product/B00MIKWEBI/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by HamidOuF** [comment]
Aujourd'hui avec Aboubakr on a réessayer de faire fonctionner le panneau Led. On a refait les branchements avec un raspberry pi0.  
Bonne nouvelle le panneau fonctionne. Il n'est pas défectueux contrairement a ce que M. Osmani a dit👒

**Comment by HamidOuF** [comment]
![20190424_202419](https://user-images.githubusercontent.com/46748199/56684103-4dbce800-66cf-11e9-9ecc-685d800278ee.jpg)

**Comment by AboubakrCH** [comment]
Le soucis maintenant c'est de pouvoir executer un programme test pour voir
un résultat concrèt. Or que quand on alimente notre panneau led et la
raspberry au même temps le panneau led s'éteint.
Il faut recherché le câblage.

**Comment by maherlaaroussi** [comment]
Après plusieurs tests sans succès, on a dû acheter une Drive Board qui permettra de faciliter le pilotage du panneau Led et d'en lier plusieurs si besoin.
Pour l'instant tout marche bien, plus qu'à coder les animations qu'on utlisera !

**Comment by othmaneMchouat** [comment]
Voile un premier test.

![test](https://user-images.githubusercontent.com/46844440/57088768-45822f80-6d03-11e9-93ee-c7cf576da22a.jpeg)

**Comment by maherlaaroussi** [comment]
Le panneau est maintenant fonctonnel, je ferme l'issue.
