### ISSUE TITLE
Utilisation de plusieurs caméras

### ISSUE THREAD

**Issue by maherlaaroussi** [institut-galilee/guessless#2]
Nous avions convenu d'utiliser plusieurs caméras pour avir plusieurs angles de visions pour reconnaître les objets, mais il apparait qu'une carte Raspberry Pi Zero WH n'a qu'un seul emplacement pour une seule caméra.
Donc soit on utilise une seule caméra, soit on utilisera d'autres composants pour relier les autres caméras.

**Comment by HamidOuF** [comment]
On pourrai utiliser un autre rasberry pour ajouter une autre camera qu en penser vous  ?

**Comment by maherlaaroussi** [comment]
Alors, deux solutions auraient pû être envisageable :  
* 1ère : Utiliser un adaptateur qui permet de pouvoir utiliser plusieurs caméras.  
* 2e : Utiliser un deuxième RPi    
  
Je pense que la 2e serait la meilleure dans notre cas vu que c'est celle qui coûte le moins chère financièrement.
