### ISSUE TITLE
Etude de l'existant 

### ISSUE THREAD

**Issue by othmaneMchouat** [institut-galilee/guessless#4]
J'ai une question à propos de la rédaction du document de l'étude de l'existant, est ce qu'il faut le séparé du cahier des charges ou bien il fait parti des sections de ce dernier?

**Comment by AboubakrCH** [comment]
Moi je crois que ça fait parti du cahier des charges, section de cahier des charges :
-Etude de l'existant
-Analyse de besoin
-Description de la solution
-Definition de la procedure

**Comment by maherlaaroussi** [comment]
Non, je pense que c'est à part, le cahier défini juste le produit, ce qui a été prévu de faire et ce qui va être fait.
L'étude de l'existant est à part !
Je peux me tromper mais c'est mon avis et je ne suis pas pro en la matière.

**Comment by HamidOuF** [comment]
J'en ai parlé avec notre encadrant et je confirme ce que Maher a dit. Effectivement c'est un document a part. Il faut d'ailleur ne pas oublié de mettre des references c est a dire citer la source de chaque modele trouvé ( un lien).
