### ISSUE TITLE
Error compiling Protobuf

### ISSUE THREAD

**Issue by maherlaaroussi** [institut-galilee/guessless#5]
Bonjour,

Je rencontre un problème en compilant Protobuf.
Toujours à la recheche d'une solution !

![20190219_155420](https://user-images.githubusercontent.com/23566811/53024368-30656680-345f-11e9-8f6b-910582507958.jpg)

**Comment by HamidOuF** [comment]
Maher j'ai fait quelque recherche de la ligne d'erreurs sur google et il faudrait peut être vérifié si tu n'as pas espace qui traine dans les noms des repertoires.
Voici un lien qui me semble intéressant.

ttps://github.com/protocolbuffers/protobuf/issues/4851#event-1712113889

**Comment by maherlaaroussi** [comment]
Je prends note de ta proposition, pour l'instant, j'ai refait un make clean + un make et après 3h toujours pas d'erreur.

**Comment by maherlaaroussi** [comment]
Je vais continuer la compilation sur du matériel plus puissant qu'un RPi Zero, je vous tiens au courant.
