### ISSUE TITLE
Proposition Nouvelle fonctionnalité

### ISSUE THREAD

**Issue by HamidOuF** [institut-galilee/guessless#6]
Je propose que l'on rajoute une nouvelle fonctionnalité de comparaison. Prenons l'exemple de deux aliments qui seront comparée par notre GuessLess.
Qu'en pensez-vous  ?

**Comment by AboubakrCH** [comment]
Moi je trouve que c'est pas mal, I agree 100%.

**Comment by maherlaaroussi** [comment]
L'idée est bonne mais ce serait comme amélioration, il faut déjà réaliser ce qui est réalisable avant la date butoir.

**Comment by HamidOuF** [comment]
Oui tu as raison. On vera plus tard pour rajouté des fonctionnalité.

Le dim. 24 févr. 2019 à 23:36, Maher LAAROUSSI <notifications@github.com> a
écrit :
